with open('fix_unlock_final.py', 'w', encoding='utf-8') as f:
    f.write(
'with open(\'nepse_scanner.py\', \'r\', encoding=\'utf-8\') as f:\n'
'    content = f.read()\n'
'\n'
'old = (\'        unlock_str = f"{e[\\\'days_left\\\']}d" if e[\\\'days_left\\\'] >= 0 else \\\'REG\\\'\\n\'\n'
'       \'        unlock_color = \\\'green\\\' if e[\\\'days_left\\\'] > 365 else \\\'yellow\\\' if e[\\\'days_left\\\'] > 90 else \\\'red\\\'\')\n'
'\n'
'new = (\'        if e[\\\'days_left\\\'] >= 0:\\n\'\n'
'       \'            unlock_str = f"{e[\\\'days_left\\\']}d"\\n\'\n'
'       \'            unlock_color = \\\'green\\\' if e[\\\'days_left\\\'] > 365 else \\\'yellow\\\' if e[\\\'days_left\\\'] > 90 else \\\'red\\\'\\n\'\n'
'       \'        else:\\n\'\n'
'       \'            unlock_str = \\\'UNLOCKED\\\'\\n\'\n'
'       \'            unlock_color = \\\'dim\\\'\')\n'
'\n'
'if old in content:\n'
'    content = content.replace(old, new, 1)\n'
'    print("OK")\n'
'else:\n'
'    print("NOT FOUND")\n'
'\n'
'with open(\'nepse_scanner.py\', \'w\', encoding=\'utf-8\') as f:\n'
'    f.write(content)\n'
)
